# Generated by Django 3.1.7 on 2021-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210227_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='gadget',
        ),
        migrations.AddField(
            model_name='articles',
            name='gadget',
            field=models.ManyToManyField(to='articles.Item'),
        ),
    ]
