# Generated by Django 3.1.7 on 2021-02-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('short_name', models.CharField(max_length=8, verbose_name='Сокращение')),
                ('description', models.CharField(max_length=255, verbose_name='Описание категории')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.DO_NOTHING, to='articles.category'),
        ),
    ]
