# Generated by Django 3.1.7 on 2021-03-05 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210305_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата заказа'),
        ),
    ]
